import sys

Import('*')

SimObject('Datapath.py')

Source('datapath.cc')
Source('dddg.cc')
Source('file_func.cpp')
Source('generic_func.cpp')
Source('opcode_func.cpp')
Source('aladdin_tlb.cc')

DebugFlag('Datapath')
