version: 2.1
orbs:
  docker: circleci/docker@1.3.0
jobs:
  build:
    docker:
      - image: xyzsam/gem5-aladdin:latest
    environment:
      ALADDIN_HOME: /root/project/src/aladdin
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem5-build-cache
      - run:
          name: Checkout dependencies
          command: git submodule update --init --recursive
      - run:
          name: Compile
          command: |
            mkdir -p build/variables
            cat \<< EOF > build/variables/X86
            TARGET_ISA = 'x86'
            CPU_MODELS = 'AtomicSimpleCPU,O3CPU,TimingSimpleCPU'
            PROTOCOL = 'MESI_Two_Level_aladdin'
            EOF
            python2.7 `which scons` build/X86/gem5.opt PROTOCOL=MESI_Two_Level_aladdin --ignore-style -j2
      - run:
          name: Running integration tests
          command: |
            python3 src/aladdin/integration-test/common/run_cpu_tests.py
            python3 src/aladdin/integration-test/common/run_ruby_tests.py
      - save_cache:
          key: v1-gem5-build-cache
          paths:
            # This DB stores all the file signatures, which SCons uses to determine
            # what has changed.
            - build/sconsign
            # This stores the conftest files used to check for dependencies.
            # Unfortunately, these C files also get recorded in the sconsign DB, so
            # if the DB thinks they're present but we don't cache them, checking for
            # dependencies will fail.
            - build/.scons_config
            - build/X86
      - store_artifacts:
          path: build/X86/gem5.opt
