#!/usr/bin/env python
# SHOC benchmark definitions

from design_sweep_types import *

bb_gemm = Benchmark("bb_gemm", "bb_gemm")
bb_gemm.set_kernels(["bb_gemm"])
bb_gemm.set_main_id(0x00000140)
bb_gemm.add_array("x", 1024, 4, PARTITION_CYCLIC)
bb_gemm.add_array("y", 1024, 4, PARTITION_CYCLIC)
bb_gemm.add_array("z", 1024, 4, PARTITION_CYCLIC)
bb_gemm.add_loop("bb_gemm", 11)
bb_gemm.add_loop("bb_gemm", 12, UNROLL_FLATTEN)
bb_gemm.add_loop("bb_gemm", 14, UNROLL_FLATTEN)

fft = Benchmark("fft", "fft")
fft.set_kernels([
    "fft1D_512", "step1", "step2", "step3", "step4", "step5", "step6",
    "step7", "step8", "step9", "step10", "step11"])
fft.set_main_id(0x00000150)
fft.add_array("work_x", 512, 4, PARTITION_CYCLIC)
fft.add_array("work_y", 512, 4, PARTITION_CYCLIC)
fft.add_array("DATA_x", 512, 4, PARTITION_CYCLIC)
fft.add_array("DATA_y", 512, 4, PARTITION_CYCLIC)
fft.add_array("data_x", 8, 4, PARTITION_COMPLETE)
fft.add_array("data_y", 8, 4, PARTITION_COMPLETE)
fft.add_array("smem", 576, 4, PARTITION_CYCLIC)
fft.add_array("reversed", 8, 4, PARTITION_COMPLETE)
fft.add_array("sin_64", 448, 4, PARTITION_COMPLETE)
fft.add_array("cos_64", 448, 4, PARTITION_COMPLETE)
fft.add_array("sin_512", 448, 4, PARTITION_COMPLETE)
fft.add_array("cos_512", 448, 4, PARTITION_COMPLETE)
fft.add_loop("step1", 16)
fft.add_loop("step1", 18, UNROLL_FLATTEN)
fft.add_loop("step1", 26, UNROLL_FLATTEN)
fft.add_loop("step1", 36, UNROLL_FLATTEN)
fft.add_loop("step2", 53)
fft.add_loop("step2", 54, UNROLL_FLATTEN)
fft.add_loop("step3", 75)
fft.add_loop("step3", 76, UNROLL_FLATTEN)
fft.add_loop("step3", 83, UNROLL_FLATTEN)
fft.add_loop("step4", 100)
fft.add_loop("step4", 101, UNROLL_FLATTEN)
fft.add_loop("step5", 122)
fft.add_loop("step5", 123, UNROLL_FLATTEN)
fft.add_loop("step5", 130, UNROLL_FLATTEN)
fft.add_loop("step6", 149)
fft.add_loop("step6", 151, UNROLL_FLATTEN)
fft.add_loop("step6", 164, UNROLL_FLATTEN)
fft.add_loop("step6", 174, UNROLL_FLATTEN)
fft.add_loop("step7", 193)
fft.add_loop("step7", 194, UNROLL_FLATTEN)
fft.add_loop("step8", 216)
fft.add_loop("step8", 217, UNROLL_FLATTEN)
fft.add_loop("step8", 224, UNROLL_FLATTEN)
fft.add_loop("step9", 243)
fft.add_loop("step9", 244, UNROLL_FLATTEN)
fft.add_loop("step10", 266)
fft.add_loop("step10", 267, UNROLL_FLATTEN)
fft.add_loop("step10", 274, UNROLL_FLATTEN)
fft.add_loop("step11", 293)
fft.add_loop("step11", 295, UNROLL_FLATTEN)
fft.add_loop("step11", 304, UNROLL_FLATTEN)

md = Benchmark("md", "md")
md.set_kernels(["md"])
md.set_main_id(0x00000160)
md.add_array("d_force_x", 32, 4, PARTITION_CYCLIC)
md.add_array("d_force_y", 32, 4, PARTITION_CYCLIC)
md.add_array("d_force_z", 32, 4, PARTITION_CYCLIC)
md.add_array("position_x", 32, 4, PARTITION_CYCLIC)
md.add_array("position_y", 32, 4, PARTITION_CYCLIC)
md.add_array("position_z", 32, 4, PARTITION_CYCLIC)
md.add_array("NL", 1024, 4, PARTITION_CYCLIC)
md.add_loop("md", 17)
md.add_loop("md", 25, UNROLL_FLATTEN)

pp_scan = Benchmark("pp_scan", "pp_scan")
pp_scan.set_kernels(["pp_scan", "local_scan", "sum_scan", "last_step_scan"])
pp_scan.set_main_id(0x00000170)
pp_scan.add_array("bucket", 2048, 4, PARTITION_CYCLIC)
pp_scan.add_array("bucket2", 2048, 4, PARTITION_CYCLIC)
pp_scan.add_array("sum", 16, 4, PARTITION_CYCLIC)
pp_scan.add_loop("sum_scan", 26)
pp_scan.add_loop("local_scan", 15)
pp_scan.add_loop("local_scan", 16, UNROLL_FLATTEN)
pp_scan.add_loop("last_step_scan", 33)
pp_scan.add_loop("last_step_scan", 34, UNROLL_FLATTEN)

reduction = Benchmark("reduction", "reduction")
reduction.set_kernels(["reduction"])
reduction.set_main_id(0x00000180)
reduction.add_array("in", 2048, 4, PARTITION_CYCLIC)
reduction.add_loop("reduction", 10)

ss_sort = Benchmark("ss_sort", "ss_sort")
ss_sort.set_kernels(["ss_sort", "init", "hist", "local_scan", "sum_scan",
                     "last_step_scan", "update"])
ss_sort.set_main_id(0x00000190)
ss_sort.add_array("a", 2048, 4, PARTITION_CYCLIC)
ss_sort.add_array("b", 2048, 4, PARTITION_CYCLIC)
ss_sort.add_array("bucket", 2048, 4, PARTITION_CYCLIC)
ss_sort.add_array("sum", 128, 4, PARTITION_CYCLIC)
ss_sort.add_loop("init", 52)
ss_sort.add_loop("hist", 61)
ss_sort.add_loop("hist", 63, UNROLL_FLATTEN)
ss_sort.add_loop("local_scan", 17)
ss_sort.add_loop("local_scan", 19, UNROLL_FLATTEN)
ss_sort.add_loop("sum_scan", 30)
ss_sort.add_loop("last_step_scan", 38)
ss_sort.add_loop("last_step_scan", 40, UNROLL_FLATTEN)
ss_sort.add_loop("update", 75)
ss_sort.add_loop("update", 77, UNROLL_FLATTEN)

stencil = Benchmark("stencil", "stencil")
stencil.set_kernels(["stencil"])
stencil.set_main_id(0x000001A0)
stencil.add_array("orig", 1024, 4, PARTITION_CYCLIC)
stencil.add_array("sol", 1024, 4, PARTITION_CYCLIC)
stencil.add_array("filter", 9, 4, PARTITION_CYCLIC)
stencil.add_loop("stencil", 11)
stencil.add_loop("stencil", 12, UNROLL_FLATTEN)

triad = Benchmark("triad", "triad")
triad.set_kernels(["triad"])
triad.set_main_id(0x000001B0)
triad.add_loop("triad", 10)
triad.add_array("a", 2048, 4, PARTITION_CYCLIC)
triad.add_array("b", 2048, 4, PARTITION_CYCLIC)
triad.add_array("c", 2048, 4, PARTITION_CYCLIC)

SHOC = [bb_gemm, fft, md, pp_scan, reduction, ss_sort, stencil, triad]
